### GET ALL USERS
GET http://localhost:5000/api/users

### GET ONE USER
GET http://localhost:5000/api/users/611a56dfd2895101f07b2ee5

### DELETE USER
DELETE  http://localhost:5000/api/users/60e99dd5ffe3c205e891d04c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYxMWE1NmRmZDI4OTUxMDFmMDdiMmVlNSIsInVzZXJuYW1lIjoibWFyYXQuc2FmaW4iLCJpc2FkbWluIjp0cnVlLCJpYXQiOjE2MjkyMDY4MDF9.OeJ7_eP4_WvpfKcpJbJ_3Kayr7adJKx3koIb9GYiJTM

### ADD USER
POST http://localhost:5000/api/users/add
Content-Type: application/json

{
    "username": "andy.murray",
    "password": "sirandy",
    "passcheck": "sirandy",
    "isadmin": true
}

### UPDATE USER
PUT http://localhost:5000/api/users/60ef94e7c02c342d2cf579d5
Content-Type: application/json

{
   "username": "andre.agassi",
    "password": "dragon",
    "passcheck": "dragon",
    "isadmin": false
}

####################################################################

### LOGIN
POST http://localhost:5000/api/auth/login
Content-Type: application/json

{
    "username": "marat.safin",
    "password": "beerclaw"
}

### LOGOUT
POST http://localhost:5000/api/auth/logout